name: Lint SCSS

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.scss'
      - '.stylelintrc*'

jobs:
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: |
          npm ci || npm i
      - name: Run Stylelint
        run: npx stylelint "**/*.scss" || true
