name: PR Filter Labels

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [ main ]

permissions:
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          sync-labels: true
